Update my_test_cli.yml

diff --git a/.github/workflows/my_test_cli.yml b/.github/workflows/my_test_cli.yml
--- a/.github/workflows/my_test_cli.yml
+++ b/.github/workflows/my_test_cli.yml
@@ -65,63 +65,27 @@ jobs:
       - name: run unit test 'OTHER'
         if: ${{ steps.check_changes.outputs.docs_only != 'true' }}
         run: |
-          set -e
-          set -o pipefail
-          set -o errexit
-
-          # solution for printing output in "set -x" trace mode without tracing the echo calls
-          shopt -s expand_aliases
-          echo_and_restore_trace() {
-            builtin echo "$@"
-            [ $trace_enabled -eq 1 ] && set -x || true
-          }
-          alias echo='{ [[ $- =~ .*x.* ]] && trace_enabled=1 || trace_enabled=0; set +x; } 2> /dev/null; echo_and_restore_trace'
-          
-          function fail {
-            echo $1 >&2
-            exit 1
-          }
-
-          function retry {
-            local n=1
-            local max=3
-            local delay=10
-            while true; do
-              "$@" && break || {
-                if [[ $n -lt $max ]]; then
-                  ((n++))
-                  echo "Command failed. Attempt $n/$max:"
-                  sleep $delay;
-                else
-                  fail "The command has failed after $n attempts."
-                fi
-              }
-            done
-          }
-
-          retry "$@"
-          
-          
-          MVN_COMMAND='mvn -B -fn -ntp'
-          MVN_COMMAND_WITH_RETRY="retry ${MVN_COMMAND}"
-          MVN_TEST_COMMAND="${MVN_COMMAND_WITH_RETRY} test"
-          echo -n "Test Group : $TEST_GROUP"
+          #mvn -B -fn clean test
+          MVN_COMMAND='mvn -B -fn clean install'
+          #MVN_COMMAND_WITH_RETRY="retry ${MVN_COMMAND}"
+          MVN_TEST_COMMAND="${MVN_COMMAND} test"
+          #echo -n "Test Group : $TEST_GROUP"
           # Test Groups  -- start --
-          function broker_group_1() {
-            $MVN_TEST_COMMAND -pl pulsar-broker -Dgroups='broker'
-          }
+          #function broker_group_1() {
+          $MVN_TEST_COMMAND -pl pulsar-broker -Dgroups='broker'
+          #}
 
-          function broker_group_2() {
-            $MVN_TEST_COMMAND -pl pulsar-broker -Dgroups='schema,utils,functions-worker,broker-io,broker-discovery,broker-compaction,broker-naming,other'
-          }
+          #function broker_group_2() {
+          #  $MVN_TEST_COMMAND -pl pulsar-broker -Dgroups='schema,utils,functions-worker,broker-io,broker-discovery,broker-compaction,broker-naming,other'
+          #}
 
-          function broker_client_api() {
-            $MVN_TEST_COMMAND -pl pulsar-broker -Dgroups='broker-api'
-          }
+          #function broker_client_api() {
+          #  $MVN_TEST_COMMAND -pl pulsar-broker -Dgroups='broker-api'
+          #}
 
-          function broker_client_impl() {
-            $MVN_TEST_COMMAND -pl pulsar-broker -Dgroups='broker-impl'
-          }
+          #function broker_client_impl() {
+          #  $MVN_TEST_COMMAND -pl pulsar-broker -Dgroups='broker-impl'
+          #}
           # prints summaries of failed tests to console
           # by using the targer/surefire-reports files
           # works only when testForkCount > 1 since that is when surefire will create reports for individual test classes
@@ -151,109 +115,109 @@ jobs:
             )
           }
 
-          function broker_flaky() {
-            echo "::endgroup::"
-            echo "::group::Running quarantined tests"
-            $MVN_COMMAND test -pl pulsar-broker -Dgroups='quarantine' -DexcludedGroups='' -DfailIfNoTests=false \
-              -DtestForkCount=2 -Dexclude='**/Replicator*Test.java' ||
-              print_testng_failures pulsar-broker/target/surefire-reports/testng-failed.xml "Quarantined test failure in" "Quarantined test failures"
+          #function broker_flaky() {
+          #  echo "::endgroup::"
+          #  echo "::group::Running quarantined tests"
+          #  $MVN_COMMAND test -pl pulsar-broker -Dgroups='quarantine' -DexcludedGroups='' -DfailIfNoTests=false \
+          #    -DtestForkCount=2 -Dexclude='**/Replicator*Test.java' ||
+          #    print_testng_failures pulsar-broker/target/surefire-reports/testng-failed.xml "Quarantined test failure in" "Quarantined test failures"
             # run quarantined Replicator tests separately
-            $MVN_COMMAND test -pl pulsar-broker -Dgroups='quarantine' -DexcludedGroups='' -DfailIfNoTests=false \
-              -DtestForkCount=2 -Dinclude='**/Replicator*Test.java' || \
-              print_testng_failures pulsar-broker/target/surefire-reports/testng-failed.xml "Quarantined test failure in" "Quarantined Replicator*Test failures"
-            echo "::endgroup::"
-            echo "::group::Running flaky tests"
-            $MVN_TEST_COMMAND -pl pulsar-broker -Dgroups='flaky' -DtestForkCount=2
-            echo "::endgroup::"
-          }
+          #  $MVN_COMMAND test -pl pulsar-broker -Dgroups='quarantine' -DexcludedGroups='' -DfailIfNoTests=false \
+          #    -DtestForkCount=2 -Dinclude='**/Replicator*Test.java' || \
+          #    print_testng_failures pulsar-broker/target/surefire-reports/testng-failed.xml "Quarantined test failure in" "Quarantined Replicator*Test failures"
+          #  echo "::endgroup::"
+          #  echo "::group::Running flaky tests"
+          #  $MVN_TEST_COMMAND -pl pulsar-broker -Dgroups='flaky' -DtestForkCount=2
+          #  echo "::endgroup::"
+          #}
 
-          function proxy() {
-            echo "::endgroup::"
-            echo "::group::Running quarantined pulsar-proxy tests"
-            $MVN_COMMAND test -pl pulsar-proxy -Dgroups='quarantine' -DexcludedGroups='' -DfailIfNoTests=false ||
-              print_testng_failures pulsar-proxy/target/surefire-reports/testng-failed.xml "Quarantined test failure in" "Quarantined test failures"
-            echo "::endgroup::"
-            echo "::group::Running pulsar-proxy tests"
-            $MVN_TEST_COMMAND -pl pulsar-proxy
-            echo "::endgroup::"
-          }
+          #function proxy() {
+          #  echo "::endgroup::"
+          #  echo "::group::Running quarantined pulsar-proxy tests"
+          #  $MVN_COMMAND test -pl pulsar-proxy -Dgroups='quarantine' -DexcludedGroups='' -DfailIfNoTests=false ||
+          #    print_testng_failures pulsar-proxy/target/surefire-reports/testng-failed.xml "Quarantined test failure in" "Quarantined test failures"
+          #  echo "::endgroup::"
+          #  echo "::group::Running pulsar-proxy tests"
+          #  $MVN_TEST_COMMAND -pl pulsar-proxy
+          #  echo "::endgroup::"
+          #}
 
-          function other() {
-            $MVN_COMMAND_WITH_RETRY clean install -PbrokerSkipTest \
-                                               -Dexclude='org/apache/pulsar/proxy/**/*.java,
-                                                          **/ManagedLedgerTest.java,
-                                                          **/TestPulsarKeyValueSchemaHandler.java,
-                                                          **/PrimitiveSchemaTest.java,
-                                                          BlobStoreManagedLedgerOffloaderTest.java'
+          #function other() {
+          #  $MVN_COMMAND_WITH_RETRY clean install -PbrokerSkipTest \
+          #                                     -Dexclude='org/apache/pulsar/proxy/**/*.java,
+          #                                                **/ManagedLedgerTest.java,
+          #                                                **/TestPulsarKeyValueSchemaHandler.java,
+          #                                                **/PrimitiveSchemaTest.java,
+          #                                                BlobStoreManagedLedgerOffloaderTest.java'
 
-            $MVN_TEST_COMMAND -pl managed-ledger -Dinclude='**/ManagedLedgerTest.java,
-                                                            **/OffloadersCacheTest.java'
+          #  $MVN_TEST_COMMAND -pl managed-ledger -Dinclude='**/ManagedLedgerTest.java,
+          #                                                  **/OffloadersCacheTest.java'
 
-            $MVN_TEST_COMMAND -pl pulsar-sql/presto-pulsar-plugin -Dinclude='**/TestPulsarKeyValueSchemaHandler.java'
+          # $MVN_TEST_COMMAND -pl pulsar-sql/presto-pulsar-plugin -Dinclude='**/TestPulsarKeyValueSchemaHandler.java'
 
-            $MVN_TEST_COMMAND -pl pulsar-client -Dinclude='**/PrimitiveSchemaTest.java'
+          #  $MVN_TEST_COMMAND -pl pulsar-client -Dinclude='**/PrimitiveSchemaTest.java'
 
-            $MVN_TEST_COMMAND -pl tiered-storage/jcloud -Dinclude='**/BlobStoreManagedLedgerOffloaderTest.java'
+           # $MVN_TEST_COMMAND -pl tiered-storage/jcloud -Dinclude='**/BlobStoreManagedLedgerOffloaderTest.java'
 
-            echo "::endgroup::"
-            local modules_with_quarantined_tests=$(git grep -l '@Test.*"quarantine"' | grep '/src/test/java/' | \
-              awk -F '/src/test/java/' '{ print $1 }' | egrep -v 'pulsar-broker|pulsar-proxy' | sort | uniq | \
-              perl -0777 -p -e 's/\n(\S)/,$1/g')
-            if [ -n "${modules_with_quarantined_tests}" ]; then
-              echo "::group::Running quarantined tests outside of pulsar-broker & pulsar-proxy (if any)"
-              $MVN_COMMAND -pl "${modules_with_quarantined_tests}" test -Dgroups='quarantine' -DexcludedGroups='' \
-                -DfailIfNoTests=false || \
-                  echo "::warning::There were test failures in the 'quarantine' test group."
-              echo "::endgroup::"
-            fi
-          }
+           # echo "::endgroup::"
+           # local modules_with_quarantined_tests=$(git grep -l '@Test.*"quarantine"' | grep '/src/test/java/' | \
+           #   awk -F '/src/test/java/' '{ print $1 }' | egrep -v 'pulsar-broker|pulsar-proxy' | sort | uniq | \
+           #   perl -0777 -p -e 's/\n(\S)/,$1/g')
+           # if [ -n "${modules_with_quarantined_tests}" ]; then
+           #   echo "::group::Running quarantined tests outside of pulsar-broker & pulsar-proxy (if any)"
+           #   $MVN_COMMAND -pl "${modules_with_quarantined_tests}" test -Dgroups='quarantine' -DexcludedGroups='' \
+            #    -DfailIfNoTests=false || \
+            #      echo "::warning::There were test failures in the 'quarantine' test group."
+            #  echo "::endgroup::"
+            #fi
+          #}
 
           # Test Groups  -- end --
 
-          TEST_GROUP='BROKER_FLAKY'
+          #TEST_GROUP='BROKER_FLAKY'
 
-          echo "Test Group : $TEST_GROUP"
+          #echo "Test Group : $TEST_GROUP"
 
-          set -x
+          #set -x
 
-          case $TEST_GROUP in
+          #case $TEST_GROUP in
 
-            BROKER_GROUP_1)
-              broker_group_1
-              ;;
+          #  BROKER_GROUP_1)
+          #    broker_group_1
+          #    ;;
 
-            BROKER_GROUP_2)
-              broker_group_2
-              ;;
+          #  BROKER_GROUP_2)
+          #    broker_group_2
+          #    ;;
 
-            BROKER_CLIENT_API)
-              broker_client_api
-              ;;
+          #  BROKER_CLIENT_API)
+          #    broker_client_api
+          #    ;;
 
-            BROKER_CLIENT_IMPL)
-              broker_client_impl
-              ;;
+          #  BROKER_CLIENT_IMPL)
+          #    broker_client_impl
+          #    ;;
 
-            BROKER_FLAKY)
-              broker_flaky
-              ;;
+          #  BROKER_FLAKY)
+          #    broker_flaky
+          #    ;;
 
-            PROXY)
-              proxy
-              ;;
+          #  PROXY)
+          #    proxy
+          #    ;;
 
-            OTHER)
-              other
-              ;;
+          #  OTHER)
+          #    other
+          #    ;;
 
-            *)
-              echo -n "INVALID TEST GROUP"
-              exit 1
-              ;;
-          esac
+          #  *)
+          #    echo -n "INVALID TEST GROUP"
+          #    exit 1
+          #    ;;
+          #esac
 
       - name: package surefire artifacts
-        if: failure()
+        #if: failure()
         run: |
           rm -rf artifacts
           mkdir artifacts
@@ -261,7 +225,7 @@ jobs:
           zip -r artifacts.zip artifacts
       - uses: actions/upload-artifact@master
         name: upload surefire-artifacts
-        if: failure()
+        #if: failure()
         with:
           name: surefire-artifacts
           path: artifacts.zip
